### ISSUE TITLE
Moment-timezone is undefined

### ISSUE THREAD

**Issue by sallu-tech** [sharetribe/ftw-daily#1266]
Everything works fine but when I click on "Edit Profile" and navigate to Availability section below Pricing, it gives me a very strange error:`
TypeError: moment_timezone_builds_moment_timezone_with_data_10_year_range_min__WEBPACK_IMPORTED_MODULE_1___default(...)(...).clone(...).tz(...) is undefined`
I am stuck on this for over a week now and can't find a solution. :(

**Comment by OtterleyW** [comment]
@sallu-tech we don't use `moment-timezone` library in ftw-daily so I'm assuming that the issue is actually related to [ftw-hourly](https://github.com/sharetribe/ftw-hourly) instead.

However, you should make sure that you have moment-timezone in your `package.json` file (see https://github.com/sharetribe/ftw-hourly/blob/c4766c47b82ed2f9b6eae9c2c87bea4af410d63b/package.json#L35) and that you have installed it with e.g. running `yarn install`. Based on the error message it seems that for some reason `moment-timezone/builds/moment-timezone-with-data-10-year-range.min`file doesn't exist.

**Comment by sallu-tech** [comment]
Hi !!
Thank you for your reply. Yes you are right that I am using ftw-hourly and
I have followed the tips that you have given. Moment-timezone library is
included in package.json and I have also used the command "yarn install"
but no luck yet. I don't know why it is giving me undefined for this
library as this is included and configured in the project. Kindly help.
Looking forward for your early response.
Thanks !!

**Comment by OtterleyW** [comment]
@sallu-tech We haven't been able to reproduce the issue so it seems likely that the problem is in your send. If you need support with your customization project I suggest you contact our support team through the chat widget in your Console or through email hello@sharetribe.com (if you haven't already done that).
