### ISSUE TITLE
Fix list has no price issue

### ISSUE THREAD

**Issue by crystalmanner** [sharetribe/ftw-daily#1333]
![image](https://user-images.githubusercontent.com/44223659/89043659-ccfb8b80-d316-11ea-8d1d-62d55f09aa3e.png)

**Comment by Gnito** [comment]
@crystalmanner this is by design. 

Currency is shown if a listing has different currency than what's set for the marketplace currency. FTW templates are made for a single currency. I assume that this happened in your local dev-environment (where you have locally changed the environment variable for currency).

* * *

If you are creating a multicurrency marketplace, I have to highlight that it is not easy to create one that fits for every scenario. In addition, Flex API doesn't have currency conversions built-in. So, if you have listings with multiple currencies, price-filter won't work correctly.

So, if you want to create a multicurrency setup on your marketplace - you need to make conscious decisions:
- Should price filtering be dropped?
- Should the real price be stored to extended data and some "marketplace search currency" used in price filter?
  (UX problem: it's difficult for users to compare listings, if search page contains listings in different currencies.)
- Should user be able to choose the currency s/he wants to view the search results?
- When to show the listing's actual "_payment_" currency?
- How to **convert between currencies**.
- Does [Stripe](https://stripe.com/docs/connect/currencies) support conversion between chosen presentment currency vs settlement currency? 
and so on.
